name: Meu primeiro pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v3
      - name: Rodar aplicacao
        run: python3 app.py
      - name: Mensagem sucesso
        run: echo "Pipeline CI/CD sucesso!"
