name: deploy de testes 

on:
  push:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: baixar o codigo
        uses: actions/checkout@v3

      - name: testing o codigo
        run: python3 app.py


  deploy: 
    runs-on: ubuntu-latest
    needs: testes
    steps:
      - name: baixar codigo
        uses: actions/checkout@v3

      - name: depoly finalizado
        run: echo " deploy finalizado com sucesso!"
