name: Meu primeiro pipeline 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: baixar o codigo
    uses: actions/checkout@v3

    - name: Rodar a aplicação
    run: python3 app.py

    - name: Mesagem de sucesso
    run: echo " Pipeline com CI/CD com sucesso"

    

